services:
  - type: web
    name: vidyut-solar-electricals
    runtime: node
    plan: free
    autoDeploy: true
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: OWNER_PANEL_KEY
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ALERT_FROM_EMAIL
        sync: false
